-- SIMPEG-DINKES KBB — Initial schema
-- All identifiers are TEXT UUIDs generated by the application layer.
-- Timestamps are ISO-8601 strings (UTC) generated by the application layer.

PRAGMA foreign_keys = ON;

-- ============================================================
-- 1. Unit Kerja (Puskesmas / UPTD / Bidang / Dinas Induk)
-- ============================================================
CREATE TABLE unit_kerja (
  id TEXT PRIMARY KEY,
  kode TEXT UNIQUE,
  nama TEXT NOT NULL,
  jenis TEXT NOT NULL CHECK (jenis IN ('DINAS_INDUK','BIDANG','UPTD','PUSKESMAS','LAINNYA')),
  parent_id TEXT REFERENCES unit_kerja(id) ON DELETE SET NULL,
  alamat TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX idx_unit_kerja_parent ON unit_kerja(parent_id);

-- ============================================================
-- 2. Users & Auth
-- ============================================================
CREATE TABLE users (
  id TEXT PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  email TEXT,
  password_hash TEXT NOT NULL,
  nama_lengkap TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('SUPER_ADMIN','ADMIN_KEPEGAWAIAN','KEPALA_BIDANG','KEPALA_DINAS','PEGAWAI')),
  unit_kerja_id TEXT REFERENCES unit_kerja(id) ON DELETE SET NULL,
  pegawai_id TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  must_change_password INTEGER NOT NULL DEFAULT 0,
  last_login_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX idx_users_unit_kerja ON users(unit_kerja_id);
CREATE INDEX idx_users_role ON users(role);

-- ============================================================
-- 3. Pegawai (data induk)
-- ============================================================
CREATE TABLE pegawai (
  id TEXT PRIMARY KEY,
  nip TEXT NOT NULL UNIQUE,
  nip_lama TEXT,
  nama TEXT NOT NULL,
  gelar_depan TEXT,
  gelar_belakang TEXT,
  tempat_lahir TEXT,
  tanggal_lahir TEXT,
  jenis_kelamin TEXT CHECK (jenis_kelamin IN ('L','P')),
  alamat TEXT,
  no_hp TEXT,
  email TEXT,
  foto_url TEXT,

  status_kepegawaian TEXT NOT NULL CHECK (status_kepegawaian IN ('CPNS','PNS','PPPK')),
  tmt_cpns TEXT,
  tmt_pns TEXT,
  status_aktif TEXT NOT NULL DEFAULT 'AKTIF' CHECK (status_aktif IN ('AKTIF','PENSIUN','MUTASI_KELUAR','CUTI_DILUAR_TANGGUNGAN','MENINGGAL','NON_AKTIF_LAINNYA')),
  tanggal_non_aktif TEXT,
  keterangan_non_aktif TEXT,

  unit_kerja_id TEXT REFERENCES unit_kerja(id) ON DELETE SET NULL,

  jenis_jabatan TEXT CHECK (jenis_jabatan IN ('STRUKTURAL','FUNGSIONAL_TERTENTU','PELAKSANA')),
  nama_jabatan TEXT,
  jenjang_jabatan TEXT,

  golongan_ruang_aktif TEXT,
  nama_pangkat_aktif TEXT,
  tmt_pangkat_aktif TEXT,

  nilai_skp_terakhir REAL,
  predikat_skp_terakhir TEXT,
  periode_skp_terakhir TEXT,

  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  created_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  updated_by TEXT REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX idx_pegawai_nama ON pegawai(nama);
CREATE INDEX idx_pegawai_unit_kerja ON pegawai(unit_kerja_id);
CREATE INDEX idx_pegawai_status_aktif ON pegawai(status_aktif);
CREATE INDEX idx_pegawai_golongan ON pegawai(golongan_ruang_aktif);
CREATE INDEX idx_pegawai_jenis_jabatan ON pegawai(jenis_jabatan);
CREATE INDEX idx_pegawai_tmt_pangkat ON pegawai(tmt_pangkat_aktif);

-- ============================================================
-- 4. Riwayat Jabatan
-- ============================================================
CREATE TABLE riwayat_jabatan (
  id TEXT PRIMARY KEY,
  pegawai_id TEXT NOT NULL REFERENCES pegawai(id) ON DELETE CASCADE,
  jenis_jabatan TEXT NOT NULL CHECK (jenis_jabatan IN ('STRUKTURAL','FUNGSIONAL_TERTENTU','PELAKSANA')),
  nama_jabatan TEXT NOT NULL,
  jenjang_jabatan TEXT,
  unit_kerja_id TEXT REFERENCES unit_kerja(id) ON DELETE SET NULL,
  no_sk TEXT,
  tanggal_sk TEXT,
  tmt_jabatan TEXT NOT NULL,
  tmt_berakhir TEXT,
  is_aktif INTEGER NOT NULL DEFAULT 1,
  keterangan TEXT,
  created_at TEXT NOT NULL,
  created_by TEXT REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX idx_riwayat_jabatan_pegawai ON riwayat_jabatan(pegawai_id);
CREATE INDEX idx_riwayat_jabatan_aktif ON riwayat_jabatan(pegawai_id, is_aktif);

-- ============================================================
-- 5. Riwayat Pangkat & Golongan
-- ============================================================
CREATE TABLE riwayat_pangkat_golongan (
  id TEXT PRIMARY KEY,
  pegawai_id TEXT NOT NULL REFERENCES pegawai(id) ON DELETE CASCADE,
  golongan_ruang TEXT NOT NULL,
  nama_pangkat TEXT NOT NULL,
  tmt_pangkat TEXT NOT NULL,
  no_sk TEXT,
  tanggal_sk TEXT,
  pejabat_penetap TEXT,
  jenis_kenaikan TEXT CHECK (jenis_kenaikan IN ('REGULER','PILIHAN_FUNGSIONAL','PENYESUAIAN_IJAZAH','PENGANGKATAN_PERTAMA','LAINNYA')),
  is_aktif INTEGER NOT NULL DEFAULT 1,
  keterangan TEXT,
  created_at TEXT NOT NULL,
  created_by TEXT REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX idx_riwayat_pangkat_pegawai ON riwayat_pangkat_golongan(pegawai_id);
CREATE INDEX idx_riwayat_pangkat_aktif ON riwayat_pangkat_golongan(pegawai_id, is_aktif);

-- ============================================================
-- 6. Riwayat Pendidikan
-- ============================================================
CREATE TABLE riwayat_pendidikan (
  id TEXT PRIMARY KEY,
  pegawai_id TEXT NOT NULL REFERENCES pegawai(id) ON DELETE CASCADE,
  jenjang_pendidikan TEXT NOT NULL,
  jurusan TEXT,
  nama_institusi TEXT,
  tahun_lulus INTEGER,
  no_ijazah TEXT,
  created_at TEXT NOT NULL,
  created_by TEXT REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX idx_riwayat_pendidikan_pegawai ON riwayat_pendidikan(pegawai_id);

-- ============================================================
-- 7. Angka Kredit (Penetapan Angka Kredit / PAK)
-- ============================================================
CREATE TABLE angka_kredit (
  id TEXT PRIMARY KEY,
  pegawai_id TEXT NOT NULL REFERENCES pegawai(id) ON DELETE CASCADE,
  nomor_pak TEXT,
  tanggal_pak TEXT,
  periode_awal TEXT,
  periode_akhir TEXT,
  angka_kredit_kumulatif REAL NOT NULL DEFAULT 0,
  unsur_utama REAL DEFAULT 0,
  pengembangan_profesi REAL DEFAULT 0,
  unsur_penunjang REAL DEFAULT 0,
  keterangan TEXT,
  is_current INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL,
  created_by TEXT REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX idx_angka_kredit_pegawai ON angka_kredit(pegawai_id);
CREATE INDEX idx_angka_kredit_current ON angka_kredit(pegawai_id, is_current);

-- ============================================================
-- 8. Parameter Aturan Kenaikan Pangkat (dikelola Super Admin)
-- ============================================================

-- 8a. Periode kenaikan pangkat nasional (mis. 1 April & 1 Oktober) — bukan hardcode
CREATE TABLE parameter_periode_kp (
  id TEXT PRIMARY KEY,
  nama_periode TEXT NOT NULL,
  bulan INTEGER NOT NULL CHECK (bulan BETWEEN 1 AND 12),
  tanggal INTEGER NOT NULL CHECK (tanggal BETWEEN 1 AND 31),
  is_active INTEGER NOT NULL DEFAULT 1,
  updated_at TEXT NOT NULL,
  updated_by TEXT REFERENCES users(id) ON DELETE SET NULL
);

-- 8b. Syarat masa kerja minimum untuk kenaikan pangkat reguler (per golongan, opsional)
CREATE TABLE parameter_masa_kerja_reguler (
  id TEXT PRIMARY KEY,
  golongan_ruang TEXT,
  masa_kerja_minimum_bulan INTEGER NOT NULL,
  keterangan TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  updated_at TEXT NOT NULL,
  updated_by TEXT REFERENCES users(id) ON DELETE SET NULL
);

-- 8c. Ambang batas angka kredit minimum per jenis jabatan fungsional & jenjang
CREATE TABLE parameter_angka_kredit_jenjang (
  id TEXT PRIMARY KEY,
  jenis_jabatan_fungsional TEXT NOT NULL,
  jenjang_jabatan TEXT NOT NULL,
  golongan_ruang TEXT,
  angka_kredit_minimum REAL NOT NULL,
  keterangan TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  updated_at TEXT NOT NULL,
  updated_by TEXT REFERENCES users(id) ON DELETE SET NULL
);

-- 8d. Syarat nilai/predikat SKP minimum
CREATE TABLE parameter_skp_minimum (
  id TEXT PRIMARY KEY,
  predikat_minimum TEXT NOT NULL,
  urutan_peringkat INTEGER NOT NULL,
  keterangan TEXT,
  is_active INTEGER NOT NULL DEFAULT 1,
  updated_at TEXT NOT NULL,
  updated_by TEXT REFERENCES users(id) ON DELETE SET NULL
);

-- 8e. Parameter umum lain (key-value), mis. reminder H-berapa bulan
CREATE TABLE parameter_umum (
  kode TEXT PRIMARY KEY,
  nama TEXT NOT NULL,
  nilai TEXT NOT NULL,
  tipe_data TEXT NOT NULL DEFAULT 'STRING' CHECK (tipe_data IN ('STRING','NUMBER','BOOLEAN','JSON')),
  keterangan TEXT,
  updated_at TEXT NOT NULL,
  updated_by TEXT REFERENCES users(id) ON DELETE SET NULL
);

-- ============================================================
-- 9. Dokumen (file pendukung, generik untuk semua entitas)
-- ============================================================
CREATE TABLE dokumen (
  id TEXT PRIMARY KEY,
  pegawai_id TEXT REFERENCES pegawai(id) ON DELETE CASCADE,
  entity_type TEXT NOT NULL CHECK (entity_type IN ('PEGAWAI','RIWAYAT_PANGKAT','RIWAYAT_PENDIDIKAN','ANGKA_KREDIT','USULAN_KP','LAINNYA')),
  entity_id TEXT,
  jenis_dokumen TEXT NOT NULL CHECK (jenis_dokumen IN ('SK_CPNS','SK_PNS','SK_PANGKAT','IJAZAH','SERTIFIKAT_DIKLAT','PAK','SKP','USULAN_KP','FOTO','LAINNYA')),
  nama_file TEXT NOT NULL,
  r2_key TEXT NOT NULL,
  mime_type TEXT,
  ukuran_bytes INTEGER,
  versi INTEGER NOT NULL DEFAULT 1,
  is_current_version INTEGER NOT NULL DEFAULT 1,
  dokumen_induk_id TEXT REFERENCES dokumen(id) ON DELETE SET NULL,
  keterangan TEXT,
  uploaded_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  uploaded_at TEXT NOT NULL
);
CREATE INDEX idx_dokumen_pegawai ON dokumen(pegawai_id);
CREATE INDEX idx_dokumen_entity ON dokumen(entity_type, entity_id);

-- ============================================================
-- 10. Status Usulan Kenaikan Pangkat (tracking tindak lanjut per periode)
-- ============================================================
CREATE TABLE status_usulan_kenaikan_pangkat (
  id TEXT PRIMARY KEY,
  pegawai_id TEXT NOT NULL REFERENCES pegawai(id) ON DELETE CASCADE,
  periode_tanggal TEXT NOT NULL,
  jenis_kenaikan TEXT NOT NULL CHECK (jenis_kenaikan IN ('REGULER','PILIHAN_FUNGSIONAL')),
  status TEXT NOT NULL DEFAULT 'BELUM_DIPROSES' CHECK (status IN ('BELUM_DIPROSES','SEDANG_DIUSULKAN','SK_TERBIT','DITUNDA')),
  catatan TEXT,
  riwayat_pangkat_golongan_id TEXT REFERENCES riwayat_pangkat_golongan(id) ON DELETE SET NULL,
  updated_by TEXT REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE(pegawai_id, periode_tanggal)
);
CREATE INDEX idx_status_usulan_periode ON status_usulan_kenaikan_pangkat(periode_tanggal);
CREATE INDEX idx_status_usulan_status ON status_usulan_kenaikan_pangkat(status);

-- ============================================================
-- 11. Log Aktivitas (audit trail)
-- ============================================================
CREATE TABLE log_aktivitas (
  id TEXT PRIMARY KEY,
  user_id TEXT REFERENCES users(id) ON DELETE SET NULL,
  username TEXT,
  aksi TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT,
  deskripsi TEXT,
  data_sebelum TEXT,
  data_sesudah TEXT,
  ip_address TEXT,
  user_agent TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX idx_log_aktivitas_entity ON log_aktivitas(entity_type, entity_id);
CREATE INDEX idx_log_aktivitas_user ON log_aktivitas(user_id);
CREATE INDEX idx_log_aktivitas_created ON log_aktivitas(created_at);

-- ============================================================
-- 12. Notifikasi (in-app reminder)
-- ============================================================
CREATE TABLE notifikasi (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  judul TEXT NOT NULL,
  pesan TEXT NOT NULL,
  tipe TEXT NOT NULL DEFAULT 'INFO' CHECK (tipe IN ('INFO','WARNING','REMINDER_KP')),
  entity_type TEXT,
  entity_id TEXT,
  is_read INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);
CREATE INDEX idx_notifikasi_user ON notifikasi(user_id, is_read);
